buildscript {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.aliyun.com/repository/central' }
        mavenCentral()
    }
    dependencies {
        classpath "net.fabricmc:fabric-loom:${loom_version}"
    }
}

apply plugin: 'net.fabricmc.fabric-loom'

loom {
    serverOnlyMinecraftJar()
}

dependencies {
    minecraft "com.mojang:minecraft:26.3"
    implementation "net.fabricmc:fabric-loader:0.19.5"
    implementation "net.fabricmc.fabric-api:fabric-api:0.160.7+26.3"

    // Jackson for config
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.16.1'
    include 'com.fasterxml.jackson.core:jackson-databind:2.16.1'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.16.1'
    include 'com.fasterxml.jackson.core:jackson-annotations:2.16.1'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.16.1'
    include 'com.fasterxml.jackson.core:jackson-core:2.16.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}
