[changelog]
# 按 convention 分组
header = "# Mirror 更新日志\n\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}
{%- endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^feat", group = "新功能" },
  { message = "^fix", group = "修复" },
  { message = "^refactor", group = "重构" },
  { message = "^perf", group = "性能优化" },
  { message = "^docs", group = "文档" },
  { message = "^chore", group = "杂项" },
  { message = "^test", group = "测试" },
  { message = "^build", group = "构建" },
  { message = "^ci", group = "CI/CD" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "V[0-9]*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "newest"
link_parsers = []
